enum IconList {
  'add-square.svg',
  'arrow-down.svg',
  'arrow-left.svg',
  'arrow-right.svg',
  'arrow-up.svg',
  'calendar.svg',
  'close-square.svg',
  'document-upload.svg',
  'edit.svg',
  'filter.svg',
  'grid.svg',
  'index.ts assets/icons/message.svg',
  'route.svg',
  'search.svg',
  'slider-vertical.svg',
  'star-filled.svg',
  'star.svg',
  'style.css assets/icons/tick-square.svg',
  'ticket.svg',
  'trash.svg',
  'user-tag.svg',
  'wallet.sv',
}
export default IconList
